#ifndef _MOTION_CFG_H
#define _MOTION_CFG_H

#include "buzzer.h"

#ifndef MANAGER_MAX_NUM_SERVOS
  #define MANAGER_MAX_NUM_SERVOS                  32
#endif

#ifndef MANAGER_MISSING_SERVOS_ALARM_NOTE
  #define MANAGER_MISSING_SERVOS_ALARM_NOTE       NOTE_SOL
#endif

#ifndef MANAGER_MISSING_SERVOS_ALARM_TIME_ON
  #define MANAGER_MISSING_SERVOS_ALARM_TIME_ON    10
#endif

#ifndef MANAGER_MISSING_SERVOS_ALARM_TIME_OFF
  #define MANAGER_MISSING_SERVOS_ALARM_TIME_OFF   100
#endif

#ifndef BALANCE_GYRO_CAL_NUM_SAMPLES
  #define BALANCE_GYRO_CAL_NUM_SAMPLES            10
#endif 

#ifndef BALANCE_GYRO_X_CHANNEL
  #define BALANCE_GYRO_X_CHANNEL                  3
#endif 

#ifndef BALANCE_GYRO_Y_CHANNEL
  #define BALANCE_GYRO_Y_CHANNEL                  4
#endif

#ifndef BALANCE_GYRO_CAL_FAILED_ALARM_NOTE
  #define BALANCE_GYRO_CAL_FAILED_ALARM_NOTE      NOTE_SOL
#endif

#ifndef BALANCE_GYRO_CAL_FAILED_ALARM_TIME_ON
  #define BALANCE_GYRO_CAL_FAILED_ALARM_TIME_ON   10
#endif

#ifndef BALANCE_GYRO_CAL_FAILED_ALARM_TIME_OFF
  #define BALANCE_GYRO_CAL_FAILED_ALARM_TIME_OFF  100
#endif

#ifndef BALANCE_MAX_CAL_GYRO_ERROR
  #define BALANCE_MAX_CAL_GYRO_ERROR              20.0
#endif

#ifndef BALANCE_FORWARD_FALL_THD_VALUE
  #define BALANCE_FORWARD_FALL_THD_VALUE          200
#endif

#ifndef BALANCE_BACKWARD_FALL_THD_VALUE
  #define BALANCE_BACKWARD_FALL_THD_VALUE         (-200)
#endif

#ifndef BALANCE_KNEE_GAIN
  #define BALANCE_KNEE_GAIN                       (2.0/54.0)
#endif

#ifndef BALANCE_ANKLE_ROLL_GAIN
  #define BALANCE_ANKLE_PITCH_GAIN                (2.0/18.0)
#endif

#ifndef BALANCE_ANKLE_ROLL_GAIN
  #define BALANCE_ANKLE_ROLL_GAIN                 (2.0/20.0)
#endif

#ifndef BALANCE_HIP_ROLL_GAIN
  #define BALANCE_HIP_ROLL_GAIN                   (2.0/40.0)
#endif

#endif
